image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: >
      nvm install &&
      npm install -g pnpm &&
      pnpm install
    command: >
      nvm install &&
      npm install -g pnpm &&
      pnpm --filter=website dev
vscode:
  extensions:
    - denoland.vscode-deno
    - github.github-vscode-theme
    - astro-build.astro-vscode
    - antfu.iconify
