export default {
  name: 'github-dark',
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '#8B949E' },
    { token: 'punctuation.definition.comment', foreground: '#8B949E' },
    { token: 'string.comment', foreground: '#8B949E' },
    { token: 'constant', foreground: '#79C0FF' },
    { token: 'entity.name.constant', foreground: '#79C0FF' },
    { token: 'variable.other.constant', foreground: '#79C0FF' },
    { token: 'variable.language', foreground: '#79C0FF' },
    { token: 'entity', foreground: '#79C0FF' },
    { token: 'entity.name', foreground: '#FFA657' },
    { token: 'meta.export.default', foreground: '#FFA657' },
    { token: 'meta.definition.variable', foreground: '#FFA657' },
    { token: 'variable.parameter.function', foreground: '#C9D1D9' },
    { token: 'meta.jsx.children', foreground: '#C9D1D9' },
    { token: 'meta.block', foreground: '#C9D1D9' },
    { token: 'meta.tag.attributes', foreground: '#C9D1D9' },
    { token: 'entity.name.constant', foreground: '#C9D1D9' },
    { token: 'meta.object.member', foreground: '#C9D1D9' },
    { token: 'meta.embedded.expression', foreground: '#C9D1D9' },
    { token: 'entity.name.function', foreground: '#D2A8FF' },
    { token: 'entity.name.tag', foreground: '#7EE787' },
    { token: 'support.class.component', foreground: '#7EE787' },
    { token: 'keyword', foreground: '#FF7B72' },
    { token: 'storage', foreground: '#FF7B72' },
    { token: 'storage.type', foreground: '#FF7B72' },
    { token: 'storage.modifier.package', foreground: '#C9D1D9' },
    { token: 'storage.modifier.import', foreground: '#C9D1D9' },
    { token: 'storage.type.java', foreground: '#C9D1D9' },
    { token: 'string', foreground: '#A5D6FF' },
    { token: 'punctuation.definition.string', foreground: '#A5D6FF' },
    {
      token: 'string punctuation.section.embedded source',
      foreground: '#A5D6FF'
    },
    { token: 'support', foreground: '#79C0FF' },
    { token: 'meta.property-name', foreground: '#79C0FF' },
    { token: 'variable', foreground: '#FFA657' },
    { token: 'variable.other', foreground: '#C9D1D9' },
    {
      token: 'invalid.broken',
      foreground: '#FFA198',
      fontStyle: 'italic'
    },
    {
      token: 'invalid.deprecated',
      foreground: '#FFA198',
      fontStyle: 'italic'
    },
    {
      token: 'invalid.illegal',
      foreground: '#FFA198',
      fontStyle: 'italic'
    },
    {
      token: 'invalid.unimplemented',
      foreground: '#FFA198',
      fontStyle: 'italic'
    },
    {
      token: 'carriage-return',
      foreground: '#0D1117',
      background: '#FF7B72',
      fontStyle: 'italic underline'
    },
    { token: 'message.error', foreground: '#FFA198' },
    { token: 'string source', foreground: '#C9D1D9' },
    { token: 'string variable', foreground: '#79C0FF' },
    { token: 'source.regexp', foreground: '#A5D6FF' },
    { token: 'string.regexp', foreground: '#A5D6FF' },
    { token: 'string.regexp.character-class', foreground: '#A5D6FF' },
    {
      token: 'string.regexp constant.character.escape',
      foreground: '#A5D6FF'
    },
    {
      token: 'string.regexp source.ruby.embedded',
      foreground: '#A5D6FF'
    },
    {
      token: 'string.regexp string.regexp.arbitrary-repitition',
      foreground: '#A5D6FF'
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: '#7EE787',
      fontStyle: 'bold'
    },
    { token: 'support.constant', foreground: '#79C0FF' },
    { token: 'support.variable', foreground: '#79C0FF' },
    { token: 'meta.module-reference', foreground: '#79C0FF' },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: '#FFA657'
    },
    { token: 'markup.heading', foreground: '#79C0FF', fontStyle: 'bold' },
    {
      token: 'markup.heading entity.name',
      foreground: '#79C0FF',
      fontStyle: 'bold'
    },
    { token: 'markup.quote', foreground: '#7EE787' },
    {
      token: 'markup.italic',
      foreground: '#C9D1D9',
      fontStyle: 'italic'
    },
    { token: 'markup.bold', foreground: '#C9D1D9', fontStyle: 'bold' },
    { token: 'markup.raw', foreground: '#79C0FF' },
    {
      token: 'markup.deleted',
      foreground: '#FFA198',
      background: '#490202'
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: '#FFA198',
      background: '#490202'
    },
    {
      token: 'punctuation.definition.deleted',
      foreground: '#FFA198',
      background: '#490202'
    },
    {
      token: 'markup.inserted',
      foreground: '#7EE787',
      background: '#04260F'
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '#7EE787',
      background: '#04260F'
    },
    {
      token: 'punctuation.definition.inserted',
      foreground: '#7EE787',
      background: '#04260F'
    },
    {
      token: 'markup.changed',
      foreground: '#FFA657',
      background: '#5A1E02'
    },
    {
      token: 'punctuation.definition.changed',
      foreground: '#FFA657',
      background: '#5A1E02'
    },
    {
      token: 'markup.ignored',
      foreground: '#161B22',
      background: '#79C0FF'
    },
    {
      token: 'markup.untracked',
      foreground: '#161B22',
      background: '#79C0FF'
    },
    {
      token: 'meta.diff.range',
      foreground: '#D2A8FF',
      fontStyle: 'bold'
    },
    { token: 'meta.diff.header', foreground: '#79C0FF' },
    { token: 'meta.separator', foreground: '#79C0FF', fontStyle: 'bold' },
    { token: 'meta.output', foreground: '#79C0FF' },
    { token: 'brackethighlighter.tag', foreground: '#8B949E' },
    { token: 'brackethighlighter.curly', foreground: '#8B949E' },
    { token: 'brackethighlighter.round', foreground: '#8B949E' },
    { token: 'brackethighlighter.square', foreground: '#8B949E' },
    { token: 'brackethighlighter.angle', foreground: '#8B949E' },
    { token: 'brackethighlighter.quote', foreground: '#8B949E' },
    { token: 'brackethighlighter.unmatched', foreground: '#FFA198' },
    {
      token: 'constant.other.reference.link',
      foreground: '#A5D6FF',
      fontStyle: 'underline'
    },
    {
      token: 'string.other.link',
      foreground: '#A5D6FF',
      fontStyle: 'underline'
    },
    { token: 'token.info-token', foreground: '#6796E6' },
    { token: 'token.warn-token', foreground: '#CD9731' },
    { token: 'token.error-token', foreground: '#F44747' },
    { token: 'token.debug-token', foreground: '#B267E6' },

    // Github dark dimmed
    // {
    //   token: 'comment',
    //   foreground: '#6A737D',
    // },
    // {
    //   token: 'punctuation.definition.comment',
    //   foreground: '#6A737D',
    // },
    // {
    //   token: 'string.comment',
    //   foreground: '#6A737D',
    // },
    // {
    //   token: 'constant',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'entity.name.constant',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'variable.other.constant',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'variable.language',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'entity',
    //   foreground: '#B392F0',
    // },
    // {
    //   token: 'entity.name',
    //   foreground: '#B392F0',
    // },
    // {
    //   token: 'variable.parameter.function',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'entity.name.tag',
    //   foreground: '#85E89D',
    // },
    // {
    //   token: 'keyword',
    //   foreground: '#F97583',
    // },
    // {
    //   token: 'storage',
    //   foreground: '#F97583',
    // },
    // {
    //   token: 'storage.type',
    //   foreground: '#F97583',
    // },
    // {
    //   token: 'storage.modifier.package',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'storage.modifier.import',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'storage.type.java',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'string',
    //   foreground: '#9ECBFF',
    // },
    // {
    //   token: 'punctuation.definition.string',
    //   foreground: '#9ECBFF',
    // },
    // {
    //   token: 'string punctuation.section.embedded source',
    //   foreground: '#9ECBFF',
    // },
    // {
    //   token: 'support',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'meta.property-name',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'variable',
    //   foreground: '#FFAB70',
    // },
    // {
    //   token: 'variable.other',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'invalid.broken',
    //   foreground: '#FDAEB7',
    //   fontStyle: 'italic'
    // },
    // {
    //   token: 'invalid.deprecated',
    //   foreground: '#FDAEB7',
    //   fontStyle: 'italic'
    // },
    // {
    //   token: 'invalid.illegal',
    //   foreground: '#FDAEB7',
    //   fontStyle: 'italic'
    // },
    // {
    //   token: 'invalid.unimplemented',
    //   foreground: '#FDAEB7',
    //   fontStyle: 'italic'
    // },
    // {
    //   token: 'carriage-return',
    //   foreground: '#24292E',
    //   background: '#F97583',
    //   fontStyle: 'italic underline'
    // },
    // {
    //   token: 'message.error',
    //   foreground: '#FDAEB7',
    // },
    // {
    //   token: 'string source',
    //   foreground: '#E1E4E8',
    // },
    // {
    //   token: 'string variable',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'source.regexp',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp.character-class',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp constant.character.escape',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp source.ruby.embedded',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp string.regexp.arbitrary-repitition',
    //   foreground: '#DBEDFF',
    // },
    // {
    //   token: 'string.regexp constant.character.escape',
    //   foreground: '#85E89D',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'support.constant',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'support.variable',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'meta.module-reference',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'punctuation.definition.list.begin.markdown',
    //   foreground: '#FFAB70',
    // },
    // {
    //   token: 'markup.heading',
    //   foreground: '#79B8FF',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'markup.heading entity.name',
    //   foreground: '#79B8FF',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'markup.quote',
    //   foreground: '#85E89D',
    // },
    // {
    //   token: 'markup.italic',
    //   foreground: '#E1E4E8',
    //   fontStyle: 'italic'
    // },
    // {
    //   token: 'markup.bold',
    //   foreground: '#E1E4E8',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'markup.raw',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'markup.deleted',
    //   foreground: '#FDAEB7',
    //   background: '#86181D',
    // },
    // {
    //   token: 'meta.diff.header.from-file',
    //   foreground: '#FDAEB7',
    //   background: '#86181D',
    // },
    // {
    //   token: 'punctuation.definition.deleted',
    //   foreground: '#FDAEB7',
    //   background: '#86181D',
    // },
    // {
    //   token: 'markup.inserted',
    //   foreground: '#85E89D',
    //   background: '#144620',
    // },
    // {
    //   token: 'meta.diff.header.to-file',
    //   foreground: '#85E89D',
    //   background: '#144620',
    // },
    // {
    //   token: 'punctuation.definition.inserted',
    //   foreground: '#85E89D',
    //   background: '#144620',
    // },
    // {
    //   token: 'markup.changed',
    //   foreground: '#FFAB70',
    //   background: '#C24E00',
    // },
    // {
    //   token: 'punctuation.definition.changed',
    //   foreground: '#FFAB70',
    //   background: '#C24E00',
    // },
    // {
    //   token: 'markup.ignored',
    //   foreground: '#2F363D',
    //   background: '#79B8FF',
    // },
    // {
    //   token: 'markup.untracked',
    //   foreground: '#2F363D',
    //   background: '#79B8FF',
    // },
    // {
    //   token: 'meta.diff.range',
    //   foreground: '#B392F0',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'meta.diff.header',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'meta.separator',
    //   foreground: '#79B8FF',
    //   fontStyle: 'bold'
    // },
    // {
    //   token: 'meta.output',
    //   foreground: '#79B8FF',
    // },
    // {
    //   token: 'brackethighlighter.tag',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.curly',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.round',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.square',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.angle',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.quote',
    //   foreground: '#D1D5DA',
    // },
    // {
    //   token: 'brackethighlighter.unmatched',
    //   foreground: '#FDAEB7',
    // },
    // {
    //   token: 'constant.other.reference.link',
    //   foreground: '#DBEDFF',
    //   fontStyle: 'underline'
    // },
    // {
    //   token: 'string.other.link',
    //   foreground: '#DBEDFF',
    //   fontStyle: 'underline'
    // },
    // {
    //   token: 'token.info-token',
    //   foreground: '#6796E6',
    // },
    // {
    //   token: 'token.warn-token',
    //   foreground: '#CD9731',
    // },
    // {
    //   token: 'token.error-token',
    //   foreground: '#F44747',
    // },
    // {
    //   token: 'token.debug-token',
    //   foreground: '#B267E6',
    // }
  ],
  colors: {
		"activityBar.activeBorder": "#f78166",
		"activityBar.background": "#0d1117",
		"activityBar.border": "#30363d",
		"activityBar.foreground": "#c9d1d9",
		"activityBar.inactiveForeground": "#8b949e",
		"activityBarBadge.background": "#1f6feb",
		"activityBarBadge.foreground": "#f0f6fc",
		"badge.background": "#1f6feb",
		"badge.foreground": "#f0f6fc",
		"breadcrumb.activeSelectionForeground": "#8b949e",
		"breadcrumb.focusForeground": "#c9d1d9",
		"breadcrumb.foreground": "#8b949e",
		"breadcrumbPicker.background": "#161b22",
		"button.background": "#238636",
		"button.foreground": "#ffffff",
		"button.hoverBackground": "#2ea043",
		"button.secondaryBackground": "#282e33",
		"button.secondaryForeground": "#c9d1d9",
		"button.secondaryHoverBackground": "#30363d",
		"checkbox.background": "#161b22",
		"checkbox.border": "#30363d",
		"debugToolBar.background": "#161b22",
		"descriptionForeground": "#8b949e",
		"diffEditor.insertedTextBackground": "#2ea04326",
		"diffEditor.removedTextBackground": "#f8514926",
		"dropdown.background": "#161b22",
		"dropdown.border": "#30363d",
		"dropdown.foreground": "#c9d1d9",
		"dropdown.listBackground": "#161b22",
		"editor.background": "#0d1117",
		"editor.findMatchBackground": "#ffd33d44",
		"editor.findMatchHighlightBackground": "#ffd33d22",
		"editor.focusedStackFrameHighlightBackground": "#3fb95025",
		"editor.foldBackground": "#6e76811a",
		"editor.foreground": "#c9d1d9",
		"editor.inactiveSelectionBackground": "#3392ff22",
		"editor.lineHighlightBackground": "#6e76811a",
		"editor.linkedEditingBackground": "#3392ff22",
		"editor.selectionBackground": "#3392ff44",
		"editor.selectionHighlightBackground": "#17e5e633",
		"editor.selectionHighlightBorder": "#17e5e600",
		"editor.stackFrameHighlightBackground": "#d2992225",
		"editor.wordHighlightBackground": "#17e5e600",
		"editor.wordHighlightBorder": "#17e5e699",
		"editor.wordHighlightStrongBackground": "#17e5e600",
		"editor.wordHighlightStrongBorder": "#17e5e666",
		"editorBracketMatch.background": "#17e5e650",
		"editorBracketMatch.border": "#17e5e600",
		"editorCursor.foreground": "#58a6ff",
		"editorGroup.border": "#30363d",
		"editorGroupHeader.tabsBackground": "#010409",
		"editorGroupHeader.tabsBorder": "#30363d",
		"editorGutter.addedBackground": "#2ea04366",
		"editorGutter.deletedBackground": "#f8514966",
		"editorGutter.modifiedBackground": "#bb800966",
		"editorIndentGuide.activeBackground": "#30363d",
		"editorIndentGuide.background": "#21262d",
		"editorLineNumber.activeForeground": "#c9d1d9",
		"editorLineNumber.foreground": "#8b949e",
		"editorOverviewRuler.border": "#010409",
		"editorWhitespace.foreground": "#484f58",
		"editorWidget.background": "#161b22",
		"errorForeground": "#f85149",
		"focusBorder": "#1f6feb",
		"foreground": "#c9d1d9",
		"gitDecoration.addedResourceForeground": "#3fb950",
		"gitDecoration.conflictingResourceForeground": "#db6d28",
		"gitDecoration.deletedResourceForeground": "#f85149",
		"gitDecoration.ignoredResourceForeground": "#484f58",
		"gitDecoration.modifiedResourceForeground": "#d29922",
		"gitDecoration.submoduleResourceForeground": "#8b949e",
		"gitDecoration.untrackedResourceForeground": "#3fb950",
		"input.background": "#0d1117",
		"input.border": "#30363d",
		"input.foreground": "#c9d1d9",
		"input.placeholderForeground": "#484f58",
		"list.activeSelectionBackground": "#6e768166",
		"list.activeSelectionForeground": "#c9d1d9",
		"list.focusBackground": "#388bfd26",
		"list.focusForeground": "#c9d1d9",
		"list.highlightForeground": "#58a6ff",
		"list.hoverBackground": "#6e76811a",
		"list.hoverForeground": "#c9d1d9",
		"list.inactiveFocusBackground": "#388bfd26",
		"list.inactiveSelectionBackground": "#6e768166",
		"list.inactiveSelectionForeground": "#c9d1d9",
		"notificationCenterHeader.background": "#161b22",
		"notificationCenterHeader.foreground": "#8b949e",
		"notifications.background": "#161b22",
		"notifications.border": "#30363d",
		"notifications.foreground": "#c9d1d9",
		"notificationsErrorIcon.foreground": "#f85149",
		"notificationsInfoIcon.foreground": "#58a6ff",
		"notificationsWarningIcon.foreground": "#d29922",
		"panel.background": "#010409",
		"panel.border": "#30363d",
		"panelInput.border": "#30363d",
		"panelTitle.activeBorder": "#f78166",
		"panelTitle.activeForeground": "#c9d1d9",
		"panelTitle.inactiveForeground": "#8b949e",
		"peekViewEditor.background": "#0d111788",
		"peekViewEditor.matchHighlightBackground": "#ffd33d33",
		"peekViewResult.background": "#0d1117",
		"peekViewResult.matchHighlightBackground": "#ffd33d33",
		"pickerGroup.border": "#30363d",
		"pickerGroup.foreground": "#8b949e",
		"progressBar.background": "#1f6feb",
		"quickInput.background": "#161b22",
		"quickInput.foreground": "#c9d1d9",
		"scrollbar.shadow": "#00000088",
		"scrollbarSlider.activeBackground": "#484f5888",
		"scrollbarSlider.background": "#484f5833",
		"scrollbarSlider.hoverBackground": "#484f5844",
		"settings.headerForeground": "#8b949e",
		"settings.modifiedItemIndicator": "#bb800966",
		"sideBar.background": "#010409",
		"sideBar.border": "#30363d",
		"sideBar.foreground": "#c9d1d9",
		"sideBarSectionHeader.background": "#010409",
		"sideBarSectionHeader.border": "#30363d",
		"sideBarSectionHeader.foreground": "#c9d1d9",
		"sideBarTitle.foreground": "#c9d1d9",
		"statusBar.background": "#0d1117",
		"statusBar.border": "#30363d",
		"statusBar.debuggingBackground": "#da3633",
		"statusBar.debuggingForeground": "#f0f6fc",
		"statusBar.foreground": "#8b949e",
		"statusBar.noFolderBackground": "#0d1117",
		"statusBarItem.prominentBackground": "#161b22",
		"tab.activeBackground": "#0d1117",
		"tab.activeBorder": "#0d1117",
		"tab.activeBorderTop": "#f78166",
		"tab.activeForeground": "#c9d1d9",
		"tab.border": "#30363d",
		"tab.hoverBackground": "#0d1117",
		"tab.inactiveBackground": "#010409",
		"tab.inactiveForeground": "#8b949e",
		"tab.unfocusedActiveBorder": "#0d1117",
		"tab.unfocusedActiveBorderTop": "#30363d",
		"tab.unfocusedHoverBackground": "#6e76811a",
		"terminal.ansiBlack": "#484f58",
		"terminal.ansiBlue": "#58a6ff",
		"terminal.ansiBrightBlack": "#6e7681",
		"terminal.ansiBrightBlue": "#79c0ff",
		"terminal.ansiBrightCyan": "#56d4dd",
		"terminal.ansiBrightGreen": "#56d364",
		"terminal.ansiBrightMagenta": "#d2a8ff",
		"terminal.ansiBrightRed": "#ffa198",
		"terminal.ansiBrightWhite": "#f0f6fc",
		"terminal.ansiBrightYellow": "#e3b341",
		"terminal.ansiCyan": "#39c5cf",
		"terminal.ansiGreen": "#3fb950",
		"terminal.ansiMagenta": "#bc8cff",
		"terminal.ansiRed": "#ff7b72",
		"terminal.ansiWhite": "#b1bac4",
		"terminal.ansiYellow": "#d29922",
		"terminal.foreground": "#8b949e",
		"textBlockQuote.background": "#010409",
		"textBlockQuote.border": "#30363d",
		"textCodeBlock.background": "#6e768166",
		"textLink.activeForeground": "#58a6ff",
		"textLink.foreground": "#58a6ff",
		"textPreformat.foreground": "#8b949e",
		"textSeparator.foreground": "#21262d",
		"titleBar.activeBackground": "#0d1117",
		"titleBar.activeForeground": "#8b949e",
		"titleBar.border": "#30363d",
		"titleBar.inactiveBackground": "#010409",
		"titleBar.inactiveForeground": "#8b949e",
		"tree.indentGuidesStroke": "#21262d",
		"welcomePage.buttonBackground": "#21262d",
		"welcomePage.buttonHoverBackground": "#30363d",
		//"activityBar.dropBorder": "#c9d1d9",
		//"banner.background": "#6e768166",
		//"banner.foreground": "#c9d1d9",
		//"banner.iconForeground": "#3794ff",
		//"breadcrumb.background": "#0d1117",
		//"charts.blue": "#3794ff",
		//"charts.foreground": "#c9d1d9",
		//"charts.green": "#89d185",
		//"charts.lines": "#c9d1d980",
		//"charts.orange": "#d18616",
		//"charts.purple": "#b180d7",
		//"charts.red": "#f14c4c",
		//"charts.yellow": "#cca700",
		//"checkbox.foreground": "#c9d1d9",
		//"debugConsole.errorForeground": "#f85149",
		//"debugConsole.infoForeground": "#3794ff",
		//"debugConsole.sourceForeground": "#c9d1d9",
		//"debugConsole.warningForeground": "#cca700",
		//"debugConsoleInputIcon.foreground": "#c9d1d9",
		//"debugExceptionWidget.background": "#420b0d",
		//"debugExceptionWidget.border": "#a31515",
		//"debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
		//"debugIcon.breakpointDisabledForeground": "#848484",
		//"debugIcon.breakpointForeground": "#e51400",
		//"debugIcon.breakpointStackframeForeground": "#89d185",
		//"debugIcon.breakpointUnverifiedForeground": "#848484",
		//"debugIcon.continueForeground": "#75beff",
		//"debugIcon.disconnectForeground": "#f48771",
		//"debugIcon.pauseForeground": "#75beff",
		//"debugIcon.restartForeground": "#89d185",
		//"debugIcon.startForeground": "#89d185",
		//"debugIcon.stepBackForeground": "#75beff",
		//"debugIcon.stepIntoForeground": "#75beff",
		//"debugIcon.stepOutForeground": "#75beff",
		//"debugIcon.stepOverForeground": "#75beff",
		//"debugIcon.stopForeground": "#f48771",
		//"debugTokenExpression.boolean": "#4e94ce",
		//"debugTokenExpression.error": "#f48771",
		//"debugTokenExpression.name": "#c586c0",
		//"debugTokenExpression.number": "#b5cea8",
		//"debugTokenExpression.string": "#ce9178",
		//"debugTokenExpression.value": "#cccccc99",
		//"debugView.exceptionLabelBackground": "#6c2022",
		//"debugView.exceptionLabelForeground": "#c9d1d9",
		//"debugView.stateLabelBackground": "#88888844",
		//"debugView.stateLabelForeground": "#c9d1d9",
		//"debugView.valueChangedHighlight": "#569cd6",
		//"diffEditor.diagonalFill": "#cccccc33",
		//"editor.findRangeHighlightBackground": "#3a3d4166",
		//"editor.hoverHighlightBackground": "#264f7840",
		//"editor.inlineValuesBackground": "#ffc80033",
		//"editor.inlineValuesForeground": "#ffffff80",
		//"editor.lineHighlightBorder": "#282828",
		//"editor.rangeHighlightBackground": "#ffffff0b",
		//"editor.snippetFinalTabstopHighlightBorder": "#525252",
		//"editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
		//"editor.symbolHighlightBackground": "#ffd33d22",
		//"editorActiveLineNumber.foreground": "#c6c6c6",
		//"editorBracketHighlight.foreground1": "#ffd700",
		//"editorBracketHighlight.foreground2": "#da70d6",
		//"editorBracketHighlight.foreground3": "#179fff",
		//"editorBracketHighlight.foreground4": "#00000000",
		//"editorBracketHighlight.foreground5": "#00000000",
		//"editorBracketHighlight.foreground6": "#00000000",
		//"editorBracketHighlight.unexpectedBracket.foreground": "#ff1212cc",
		//"editorCodeLens.foreground": "#999999",
		//"editorError.foreground": "#f14c4c",
		//"editorGhostText.foreground": "#ffffff56",
		//"editorGroup.dropBackground": "#53595d80",
		//"editorGroupHeader.noTabsBackground": "#0d1117",
		//"editorGutter.background": "#0d1117",
		//"editorGutter.commentRangeForeground": "#c5c5c5",
		//"editorGutter.foldingControlForeground": "#c5c5c5",
		//"editorHint.foreground": "#eeeeeeb3",
		//"editorHoverWidget.background": "#161b22",
		//"editorHoverWidget.border": "#454545",
		//"editorHoverWidget.foreground": "#c9d1d9",
		//"editorHoverWidget.statusBarBackground": "#1a2029",
		//"editorInfo.foreground": "#3794ff",
		//"editorInlayHint.background": "#1f6feb99",
		//"editorInlayHint.foreground": "#f0f6fccc",
		//"editorInlayHint.parameterBackground": "#1f6feb99",
		//"editorInlayHint.parameterForeground": "#f0f6fccc",
		//"editorInlayHint.typeBackground": "#1f6feb99",
		//"editorInlayHint.typeForeground": "#f0f6fccc",
		//"editorLightBulb.foreground": "#ffcc00",
		//"editorLightBulbAutoFix.foreground": "#75beff",
		//"editorLink.activeForeground": "#4e94ce",
		//"editorMarkerNavigation.background": "#0d1117",
		//"editorMarkerNavigationError.background": "#f14c4c",
		//"editorMarkerNavigationError.headerBackground": "#f14c4c1a",
		//"editorMarkerNavigationInfo.background": "#3794ff",
		//"editorMarkerNavigationInfo.headerBackground": "#3794ff1a",
		//"editorMarkerNavigationWarning.background": "#cca700",
		//"editorMarkerNavigationWarning.headerBackground": "#cca7001a",
		//"editorOverviewRuler.addedForeground": "#2ea0433d",
		//"editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
		//"editorOverviewRuler.commonContentForeground": "#60606066",
		//"editorOverviewRuler.currentContentForeground": "#40c8ae80",
		//"editorOverviewRuler.deletedForeground": "#f851493d",
		//"editorOverviewRuler.errorForeground": "#ff1212b3",
		//"editorOverviewRuler.findMatchForeground": "#d186167e",
		//"editorOverviewRuler.incomingContentForeground": "#40a6ff80",
		//"editorOverviewRuler.infoForeground": "#3794ff",
		//"editorOverviewRuler.modifiedForeground": "#bb80093d",
		//"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
		//"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
		//"editorOverviewRuler.warningForeground": "#cca700",
		//"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
		//"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
		//"editorPane.background": "#0d1117",
		//"editorRuler.foreground": "#5a5a5a",
		//"editorSuggestWidget.background": "#161b22",
		//"editorSuggestWidget.border": "#454545",
		//"editorSuggestWidget.focusHighlightForeground": "#58a6ff",
		//"editorSuggestWidget.foreground": "#c9d1d9",
		//"editorSuggestWidget.highlightForeground": "#58a6ff",
		//"editorSuggestWidget.selectedBackground": "#6e768166",
		//"editorSuggestWidget.selectedForeground": "#c9d1d9",
		//"editorUnnecessaryCode.opacity": "#000000aa",
		//"editorWarning.foreground": "#cca700",
		//"editorWidget.border": "#454545",
		//"editorWidget.foreground": "#c9d1d9",
		//"extensionBadge.remoteBackground": "#1f6feb",
		//"extensionBadge.remoteForeground": "#f0f6fc",
		//"extensionButton.prominentBackground": "#238636",
		//"extensionButton.prominentForeground": "#ffffff",
		//"extensionButton.prominentHoverBackground": "#2ea043",
		//"extensionIcon.starForeground": "#ff8e00",
		//"gitDecoration.renamedResourceForeground": "#73c991",
		//"gitDecoration.stageDeletedResourceForeground": "#c74e39",
		//"gitDecoration.stageModifiedResourceForeground": "#e2c08d",
		//"icon.foreground": "#c5c5c5",
		//"inputOption.activeBackground": "#1f6feb66",
		//"inputOption.activeBorder": "#007acc00",
		//"inputOption.activeForeground": "#ffffff",
		//"inputValidation.errorBackground": "#5a1d1d",
		//"inputValidation.errorBorder": "#be1100",
		//"inputValidation.infoBackground": "#063b49",
		//"inputValidation.infoBorder": "#007acc",
		//"inputValidation.warningBackground": "#352a05",
		//"inputValidation.warningBorder": "#b89500",
		//"interactive.activeCodeBorder": "#3794ff",
		//"interactive.inactiveCodeBorder": "#6e768166",
		//"issues.closed": "#cb2431",
		//"issues.newIssueDecoration": "#ffffff48",
		//"issues.open": "#22863a",
		//"keybindingLabel.background": "#8080802b",
		//"keybindingLabel.border": "#33333399",
		//"keybindingLabel.bottomBorder": "#44444499",
		//"keybindingLabel.foreground": "#cccccc",
		//"list.deemphasizedForeground": "#8c8c8c",
		//"list.dropBackground": "#062f4a",
		//"list.errorForeground": "#f88070",
		//"list.filterMatchBackground": "#ffd33d22",
		//"list.focusHighlightForeground": "#58a6ff",
		//"list.focusOutline": "#1f6feb",
		//"list.invalidItemForeground": "#b89500",
		//"list.warningForeground": "#cca700",
		//"listFilterWidget.background": "#653723",
		//"listFilterWidget.noMatchesOutline": "#be1100",
		//"listFilterWidget.outline": "#00000000",
		//"menu.background": "#161b22",
		//"menu.foreground": "#c9d1d9",
		//"menu.selectionBackground": "#6e768166",
		//"menu.selectionForeground": "#c9d1d9",
		//"menu.separatorBackground": "#bbbbbb",
		//"menubar.selectionBackground": "#ffffff1a",
		//"menubar.selectionForeground": "#8b949e",
		//"merge.commonContentBackground": "#60606029",
		//"merge.commonHeaderBackground": "#60606066",
		//"merge.currentContentBackground": "#40c8ae33",
		//"merge.currentHeaderBackground": "#40c8ae80",
		//"merge.incomingContentBackground": "#40a6ff33",
		//"merge.incomingHeaderBackground": "#40a6ff80",
		//"minimap.errorHighlight": "#ff1212b3",
		//"minimap.findMatchHighlight": "#d18616",
		//"minimap.foregroundOpacity": "#000000",
		//"minimap.selectionHighlight": "#264f78",
		//"minimap.selectionOccurrenceHighlight": "#676767",
		//"minimap.warningHighlight": "#cca700",
		//"minimapGutter.addedBackground": "#587c0c",
		//"minimapGutter.deletedBackground": "#94151b",
		//"minimapGutter.modifiedBackground": "#0c7d9d",
		//"minimapSlider.activeBackground": "#484f5844",
		//"minimapSlider.background": "#484f581a",
		//"minimapSlider.hoverBackground": "#484f5822",
		//"notebook.cellBorderColor": "#6e768166",
		//"notebook.cellEditorBackground": "#c9d1d90a",
		//"notebook.cellInsertionIndicator": "#1f6feb",
		//"notebook.cellStatusBarItemHoverBackground": "#ffffff26",
		//"notebook.cellToolbarSeparator": "#80808059",
		//"notebook.focusedCellBorder": "#1f6feb",
		//"notebook.focusedEditorBorder": "#1f6feb",
		//"notebook.inactiveFocusedCellBorder": "#6e768166",
		//"notebook.selectedCellBackground": "#6e768166",
		//"notebook.selectedCellBorder": "#6e768166",
		//"notebook.symbolHighlightBackground": "#ffffff0b",
		//"notebookScrollbarSlider.activeBackground": "#484f5888",
		//"notebookScrollbarSlider.background": "#484f5833",
		//"notebookScrollbarSlider.hoverBackground": "#484f5844",
		//"notebookStatusErrorIcon.foreground": "#f85149",
		//"notebookStatusRunningIcon.foreground": "#c9d1d9",
		//"notebookStatusSuccessIcon.foreground": "#89d185",
		//"notificationLink.foreground": "#58a6ff",
		//"panel.dropBorder": "#c9d1d9",
		//"panelSection.border": "#30363d",
		//"panelSection.dropBackground": "#53595d80",
		//"panelSectionHeader.background": "#80808033",
		//"peekView.border": "#3794ff",
		//"peekViewEditorGutter.background": "#0d111788",
		//"peekViewResult.fileForeground": "#ffffff",
		//"peekViewResult.lineForeground": "#bbbbbb",
		//"peekViewResult.selectionBackground": "#3399ff33",
		//"peekViewResult.selectionForeground": "#ffffff",
		//"peekViewTitle.background": "#3794ff1a",
		//"peekViewTitleDescription.foreground": "#ccccccb3",
		//"peekViewTitleLabel.foreground": "#ffffff",
		//"ports.iconRunningProcessForeground": "#1f6feb",
		//"problemsErrorIcon.foreground": "#f14c4c",
		//"problemsInfoIcon.foreground": "#3794ff",
		//"problemsWarningIcon.foreground": "#cca700",
		//"quickInputList.focusBackground": "#6e768166",
		//"quickInputList.focusForeground": "#c9d1d9",
		//"quickInputTitle.background": "#ffffff1b",
		//"sash.hoverBorder": "#1f6feb",
		//"scm.providerBorder": "#454545",
		//"searchEditor.findMatchBackground": "#ffd33d16",
		//"searchEditor.textInputBorder": "#30363d",
		//"settings.checkboxBackground": "#161b22",
		//"settings.checkboxBorder": "#30363d",
		//"settings.checkboxForeground": "#c9d1d9",
		//"settings.dropdownBackground": "#161b22",
		//"settings.dropdownBorder": "#30363d",
		//"settings.dropdownForeground": "#c9d1d9",
		//"settings.dropdownListBorder": "#454545",
		//"settings.focusedRowBackground": "#80808024",
		//"settings.focusedRowBorder": "#ffffff1f",
		//"settings.numberInputBackground": "#0d1117",
		//"settings.numberInputBorder": "#30363d",
		//"settings.numberInputForeground": "#c9d1d9",
		//"settings.rowHoverBackground": "#80808012",
		//"settings.textInputBackground": "#0d1117",
		//"settings.textInputBorder": "#30363d",
		//"settings.textInputForeground": "#c9d1d9",
		//"sideBar.dropBackground": "#53595d80",
		//"sideBySideEditor.border": "#30363d",
		//"statusBar.debuggingBorder": "#30363d",
		//"statusBar.noFolderBorder": "#30363d",
		//"statusBar.noFolderForeground": "#8b949e",
		//"statusBarItem.activeBackground": "#ffffff2e",
		//"statusBarItem.errorBackground": "#b91007",
		//"statusBarItem.errorForeground": "#ffffff",
		//"statusBarItem.hoverBackground": "#ffffff1f",
		//"statusBarItem.prominentForeground": "#8b949e",
		//"statusBarItem.prominentHoverBackground": "#0000004d",
		//"statusBarItem.remoteBackground": "#1f6feb",
		//"statusBarItem.remoteForeground": "#f0f6fc",
		//"statusBarItem.warningBackground": "#7a6400",
		//"statusBarItem.warningForeground": "#ffffff",
		//"symbolIcon.arrayForeground": "#c9d1d9",
		//"symbolIcon.booleanForeground": "#c9d1d9",
		//"symbolIcon.classForeground": "#ee9d28",
		//"symbolIcon.colorForeground": "#c9d1d9",
		//"symbolIcon.constantForeground": "#c9d1d9",
		//"symbolIcon.constructorForeground": "#b180d7",
		//"symbolIcon.enumeratorForeground": "#ee9d28",
		//"symbolIcon.enumeratorMemberForeground": "#75beff",
		//"symbolIcon.eventForeground": "#ee9d28",
		//"symbolIcon.fieldForeground": "#75beff",
		//"symbolIcon.fileForeground": "#c9d1d9",
		//"symbolIcon.folderForeground": "#c9d1d9",
		//"symbolIcon.functionForeground": "#b180d7",
		//"symbolIcon.interfaceForeground": "#75beff",
		//"symbolIcon.keyForeground": "#c9d1d9",
		//"symbolIcon.keywordForeground": "#c9d1d9",
		//"symbolIcon.methodForeground": "#b180d7",
		//"symbolIcon.moduleForeground": "#c9d1d9",
		//"symbolIcon.namespaceForeground": "#c9d1d9",
		//"symbolIcon.nullForeground": "#c9d1d9",
		//"symbolIcon.numberForeground": "#c9d1d9",
		//"symbolIcon.objectForeground": "#c9d1d9",
		//"symbolIcon.operatorForeground": "#c9d1d9",
		//"symbolIcon.packageForeground": "#c9d1d9",
		//"symbolIcon.propertyForeground": "#c9d1d9",
		//"symbolIcon.referenceForeground": "#c9d1d9",
		//"symbolIcon.snippetForeground": "#c9d1d9",
		//"symbolIcon.stringForeground": "#c9d1d9",
		//"symbolIcon.structForeground": "#c9d1d9",
		//"symbolIcon.textForeground": "#c9d1d9",
		//"symbolIcon.typeParameterForeground": "#c9d1d9",
		//"symbolIcon.unitForeground": "#c9d1d9",
		//"symbolIcon.variableForeground": "#75beff",
		//"tab.activeModifiedBorder": "#3399cc",
		//"tab.inactiveModifiedBorder": "#3399cc80",
		//"tab.lastPinnedBorder": "#21262d",
		//"tab.unfocusedActiveBackground": "#0d1117",
		//"tab.unfocusedActiveForeground": "#c9d1d980",
		//"tab.unfocusedActiveModifiedBorder": "#3399cc80",
		//"tab.unfocusedInactiveBackground": "#010409",
		//"tab.unfocusedInactiveForeground": "#8b949e80",
		//"tab.unfocusedInactiveModifiedBorder": "#3399cc40",
		//"terminal.border": "#30363d",
		//"terminal.dropBackground": "#53595d80",
		//"terminal.selectionBackground": "#ffffff40",
		//"terminal.tab.activeBorder": "#0d1117",
		//"testing.iconErrored": "#f14c4c",
		//"testing.iconFailed": "#f14c4c",
		//"testing.iconPassed": "#73c991",
		//"testing.iconQueued": "#cca700",
		//"testing.iconSkipped": "#848484",
		//"testing.iconUnset": "#848484",
		//"testing.message.error.decorationForeground": "#f14c4c",
		//"testing.message.error.lineBackground": "#ff000033",
		//"testing.message.info.decorationForeground": "#c9d1d980",
		//"testing.peekBorder": "#f14c4c",
		//"testing.peekHeaderBackground": "#f14c4c1a",
		//"testing.runAction": "#73c991",
		//"toolbar.activeBackground": "#63666750",
		//"toolbar.hoverBackground": "#5a5d5e50",
		//"tree.tableColumnsBorder": "#cccccc20",
		//"welcomePage.progress.background": "#0d1117",
		//"welcomePage.progress.foreground": "#58a6ff",
		//"welcomePage.tileBackground": "#161b22",
		//"welcomePage.tileHoverBackground": "#1a2029",
		//"welcomePage.tileShadow.": "#0000005c",
		//"widget.shadow": "#0000005c",
		//"activityBar.activeBackground": null,
		//"activityBar.activeFocusBorder": null,
		//"button.border": null,
		//"contrastActiveBorder": null,
		//"contrastBorder": null,
		//"debugToolBar.border": null,
		//"diffEditor.border": null,
		//"diffEditor.insertedTextBorder": null,
		//"diffEditor.removedTextBorder": null,
		//"editor.findMatchBorder": null,
		//"editor.findMatchHighlightBorder": null,
		//"editor.findRangeHighlightBorder": null,
		//"editor.rangeHighlightBorder": null,
		//"editor.selectionForeground": null,
		//"editor.snippetFinalTabstopHighlightBackground": null,
		//"editor.snippetTabstopHighlightBorder": null,
		//"editor.symbolHighlightBorder": null,
		//"editorCursor.background": null,
		//"editorError.background": null,
		//"editorError.border": null,
		//"editorGhostText.border": null,
		//"editorGroup.emptyBackground": null,
		//"editorGroup.focusedEmptyBorder": null,
		//"editorGroupHeader.border": null,
		//"editorHint.border": null,
		//"editorInfo.background": null,
		//"editorInfo.border": null,
		//"editorOverviewRuler.background": null,
		//"editorSuggestWidget.selectedIconForeground": null,
		//"editorUnnecessaryCode.border": null,
		//"editorWarning.background": null,
		//"editorWarning.border": null,
		//"editorWidget.resizeBorder": null,
		//"inputValidation.errorForeground": null,
		//"inputValidation.infoForeground": null,
		//"inputValidation.warningForeground": null,
		//"list.activeSelectionIconForeground": null,
		//"list.filterMatchBorder": null,
		//"list.inactiveFocusOutline": null,
		//"list.inactiveSelectionIconForeground": null,
		//"menu.border": null,
		//"menu.selectionBorder": null,
		//"menubar.selectionBorder": null,
		//"merge.border": null,
		//"minimap.background": null,
		//"notebook.cellHoverBackground": null,
		//"notebook.focusedCellBackground": null,
		//"notebook.inactiveSelectedCellBorder": null,
		//"notebook.outputContainerBackgroundColor": null,
		//"notebook.outputContainerBorderColor": null,
		//"notificationCenter.border": null,
		//"notificationToast.border": null,
		//"panelSectionHeader.border": null,
		//"panelSectionHeader.foreground": null,
		//"peekViewEditor.matchHighlightBorder": null,
		//"quickInput.list.focusBackground": null,
		//"quickInputList.focusIconForeground": null,
		//"searchEditor.findMatchBorder": null,
		//"selection.background": null,
		//"tab.hoverBorder": null,
		//"tab.hoverForeground": null,
		//"tab.unfocusedHoverBorder": null,
		//"tab.unfocusedHoverForeground": null,
		//"terminal.background": null,
		//"terminalCursor.background": null,
		//"terminalCursor.foreground": null,
		//"testing.message.info.lineBackground": null,
		//"toolbar.hoverOutline": null,
		//"walkThrough.embeddedEditorBackground": null,
		//"welcomePage.background": null,
		//"window.activeBorder": null,
		//"window.inactiveBorder": null




    // --- Github dark dimmed
    // 'activityBar.activeBackground': '#3399FF',
    // 'activityBar.activeBorder': '#BF0060',
    // 'activityBar.background': '#3399FF',
    // 'activityBar.border': '#1B1F23',
    // 'activityBar.foreground': '#15202B',
    // 'activityBar.inactiveForeground': '#15202B99',
    // 'activityBarBadge.background': '#BF0060',
    // 'activityBarBadge.foreground': '#E7E7E7',
    // 'badge.background': '#044289',
    // 'badge.foreground': '#C8E1FF',
    // 'breadcrumb.activeSelectionForeground': '#D1D5DA',
    // 'breadcrumb.focusForeground': '#E1E4E8',
    // 'breadcrumb.foreground': '#959DA5',
    // 'breadcrumbPicker.background': '#2B3036',
    // 'button.background': '#176F2C',
    // 'button.foreground': '#DCFFE4',
    // 'button.hoverBackground': '#22863A',
    // 'button.secondaryBackground': '#444D56',
    // 'button.secondaryForeground': '#FFFFFF',
    // 'button.secondaryHoverBackground': '#586069',
    // 'checkbox.background': '#444D56',
    // 'checkbox.border': '#1B1F23',
    // 'debugToolBar.background': '#2B3036',
    // descriptionForeground: '#959DA5',
    // 'diffEditor.insertedTextBackground': '#28A74530',
    // 'diffEditor.removedTextBackground': '#D73A4930',
    
    // "minimap.background": "#24292E",
    // "minimap.hoverBackground": "#00000028",

    // 'dropdown.background': '#2F363D',
    // 'dropdown.border': '#1B1F23',
    // 'dropdown.foreground': '#E1E4E8',
    // 'dropdown.listBackground': '#24292E',
    // 'editor.background': '#24292E',
    // 'editor.findMatchBackground': '#FFD33D44',
    // 'editor.findMatchHighlightBackground': '#FFD33D22',
    // 'editor.focusedStackFrameHighlightBackground': '#2B6A3033',
    // 'editor.foldBackground': '#58606915',
    // 'editor.foreground': '#E1E4E8',
    // 'editor.inactiveSelectionBackground': '#3392FF22',
    // 'editor.lineHighlightBackground': '#2B3036',
    // 'editor.linkedEditingBackground': '#3392FF22',
    // 'editor.selectionBackground': '#3392FF44',
    // 'editor.selectionHighlightBackground': '#17E5E633',
    // 'editor.selectionHighlightBorder': '#17E5E600',
    // 'editor.stackFrameHighlightBackground': '#C6902625',
    // 'editor.wordHighlightBackground': '#17E5E600',
    // 'editor.wordHighlightBorder': '#17E5E699',
    // 'editor.wordHighlightStrongBackground': '#17E5E600',
    // 'editor.wordHighlightStrongBorder': '#17E5E666',
    // 'editorBracketMatch.background': '#17E5E650',
    // 'editorBracketMatch.border': '#17E5E600',
    // 'editorCursor.foreground': '#C8E1FF',
    // 'editorGroup.border': '#1B1F23',
    // 'editorGroupHeader.tabsBackground': '#1F2428',
    // 'editorGroupHeader.tabsBorder': '#1B1F23',
    // 'editorGutter.addedBackground': '#28A745',
    // 'editorGutter.deletedBackground': '#EA4A5A',
    // 'editorGutter.modifiedBackground': '#2188FF',
    // 'editorIndentGuide.activeBackground': '#444D56',
    // 'editorIndentGuide.background': '#2F363D',
    // 'editorLineNumber.activeForeground': '#E1E4E8',
    // 'editorLineNumber.foreground': '#444D56',
    // 'editorOverviewRuler.border': '#1B1F23',
    // 'editorWhitespace.foreground': '#444D56',
    // 'editorWidget.background': '#1F2428',
    // errorForeground: '#F97583',
    // focusBorder: '#005CC5',
    // foreground: '#D1D5DA',
    // 'gitDecoration.addedResourceForeground': '#34D058',
    // 'gitDecoration.conflictingResourceForeground': '#FFAB70',
    // 'gitDecoration.deletedResourceForeground': '#EA4A5A',
    // 'gitDecoration.ignoredResourceForeground': '#6A737D',
    // 'gitDecoration.modifiedResourceForeground': '#79B8FF',
    // 'gitDecoration.submoduleResourceForeground': '#6A737D',
    // 'gitDecoration.untrackedResourceForeground': '#34D058',
    // 'input.background': '#2F363D',
    // 'input.border': '#1B1F23',
    // 'input.foreground': '#E1E4E8',
    // 'input.placeholderForeground': '#959DA5',
    // 'list.activeSelectionBackground': '#39414A',
    // 'list.activeSelectionForeground': '#E1E4E8',
    // 'list.focusBackground': '#044289',
    // 'list.hoverBackground': '#282E34',
    // 'list.hoverForeground': '#E1E4E8',
    // 'list.inactiveFocusBackground': '#1D2D3E',
    // 'list.inactiveSelectionBackground': '#282E34',
    // 'list.inactiveSelectionForeground': '#E1E4E8',
    // 'notificationCenterHeader.background': '#24292E',
    // 'notificationCenterHeader.foreground': '#959DA5',
    // 'notifications.background': '#2F363D',
    // 'notifications.border': '#1B1F23',
    // 'notifications.foreground': '#E1E4E8',
    // 'notificationsErrorIcon.foreground': '#EA4A5A',
    // 'notificationsInfoIcon.foreground': '#79B8FF',
    // 'notificationsWarningIcon.foreground': '#FFAB70',
    // 'panel.background': '#1F2428',
    // 'panel.border': '#1B1F23',
    // 'panelInput.border': '#2F363D',
    // 'panelTitle.activeBorder': '#F9826C',
    // 'panelTitle.activeForeground': '#E1E4E8',
    // 'panelTitle.inactiveForeground': '#959DA5',
    // 'peekViewEditor.background': '#1F242888',
    // 'peekViewEditor.matchHighlightBackground': '#FFD33D33',
    // 'peekViewResult.background': '#1F2428',
    // 'peekViewResult.matchHighlightBackground': '#FFD33D33',
    // 'pickerGroup.border': '#444D56',
    // 'pickerGroup.foreground': '#E1E4E8',
    // 'progressBar.background': '#0366D6',
    // 'quickInput.background': '#24292E',
    // 'quickInput.foreground': '#E1E4E8',
    // 'scrollbar.shadow': '#00000088',
    // 'settings.headerForeground': '#E1E4E8',
    // 'settings.modifiedItemIndicator': '#0366D6',
    // 'sideBar.background': '#1F2428',
    // 'sideBar.border': '#1B1F23',
    // 'sideBar.foreground': '#D1D5DA',
    // 'sideBarSectionHeader.background': '#1F2428',
    // 'sideBarSectionHeader.border': '#1B1F23',
    // 'sideBarSectionHeader.foreground': '#E1E4E8',
    // 'sideBarTitle.foreground': '#E1E4E8',
    // 'statusBar.background': '#007FFF',
    // 'statusBar.border': '#1B1F23',
    // 'statusBar.debuggingBackground': '#931C06',
    // 'statusBar.debuggingForeground': '#FFFFFF',
    // 'statusBar.foreground': '#E7E7E7',
    // 'statusBar.noFolderBackground': '#24292E',
    // 'statusBarItem.hoverBackground': '#3399FF',
    // 'statusBarItem.prominentBackground': '#282E34',
    // 'tab.activeBackground': '#24292E',
    // 'tab.activeBorder': '#24292E',
    // 'tab.activeBorderTop': '#F9826C',
    // 'tab.activeForeground': '#E1E4E8',
    // 'tab.border': '#1B1F23',
    // 'tab.hoverBackground': '#24292E',
    // 'tab.inactiveBackground': '#1F2428',
    // 'tab.inactiveForeground': '#959DA5',
    // 'tab.unfocusedActiveBorder': '#24292E',
    // 'tab.unfocusedActiveBorderTop': '#1B1F23',
    // 'tab.unfocusedHoverBackground': '#24292E',
    // 'terminal.foreground': '#D1D5DA',
    // 'textBlockQuote.background': '#24292E',
    // 'textBlockQuote.border': '#444D56',
    // 'textCodeBlock.background': '#2F363D',
    // 'textLink.activeForeground': '#C8E1FF',
    // 'textLink.foreground': '#79B8FF',
    // 'textPreformat.foreground': '#D1D5DA',
    // 'textSeparator.foreground': '#586069',
    // 'titleBar.activeBackground': '#007FFF',
    // 'titleBar.activeForeground': '#E7E7E7',
    // 'titleBar.border': '#1B1F23',
    // 'titleBar.inactiveBackground': '#007FFF99',
    // 'titleBar.inactiveForeground': '#E7E7E799',
    // 'tree.indentGuidesStroke': '#2F363D',
    // 'welcomePage.buttonBackground': '#2F363D',
    // 'welcomePage.buttonHoverBackground': '#444D56'
  }
}