(function(p,g){typeof exports=="object"&&typeof module!="undefined"?g(exports):typeof define=="function"&&define.amd?define(["exports"],g):(p=typeof globalThis!="undefined"?globalThis:p||self,g(p.bundlejs={}))})(this,function(p){"use strict";const g=(e,o=300,n)=>{let i;return function(...s){let c=this,l=()=>{i=null,n||e.apply(c,s)},m=n&&!i;clearTimeout(i),i=setTimeout(l,o),m&&e.apply(c,s)}},b=new Map,E="EXTERNAL_FETCHES",A=async(e,o,n)=>{let i=await fetch(o,n),s=i.clone();return"caches"in globalThis?e.put(o,s):b.set(o,s),i},T=async(e,o=!1,n)=>{let i=new Request(e.toString()),s,c,l;return"caches"in globalThis?(c=await caches.open(E),l=await c.match(i)):l=b.get(i),s=l,l?o||A(c,i,n):s=await A(c,i,n),s.clone()};var x="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-$",w={};function _(e,o){if(!w[e]){w[e]={};for(let n=0;n<e.length;n++)w[e][e.charAt(n)]=n}return w[e][o]}function N(e){return e==null?"":e==""?null:(e=e.replaceAll(" ","+"),R(e.length,32,o=>_(x,e.charAt(o))))}function R(e,o,n){let i=[],s=4,c=4,l=3,m="",y=[],C,d,a,u,f,r,h,t={val:n(0),position:o,index:1};for(C=0;C<3;C+=1)i[C]=C;for(a=0,f=Math.pow(2,2),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;switch(a){case 0:for(a=0,f=Math.pow(2,8),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;h=String.fromCharCode(a);break;case 1:for(a=0,f=Math.pow(2,16),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;h=String.fromCharCode(a);break;case 2:return""}for(i[3]=h,d=h,y.push(h);;){if(t.index>e)return"";for(a=0,f=Math.pow(2,l),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;switch(h=a){case 0:for(a=0,f=Math.pow(2,8),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;i[c++]=String.fromCharCode(a),h=c-1,s--;break;case 1:for(a=0,f=Math.pow(2,16),r=1;r!=f;)u=t.val&t.position,t.position>>=1,t.position==0&&(t.position=o,t.val=n(t.index++)),a|=(u>0?1:0)*r,r<<=1;i[c++]=String.fromCharCode(a),h=c-1,s--;break;case 2:return y.join("")}if(s==0&&(s=Math.pow(2,l),l++),i[h])m=i[h];else if(h===c&&typeof d=="string")m=d+d.charAt(0);else return null;y.push(m),i[c++]=d+m.charAt(0),s--,d=m,s==0&&(s=Math.pow(2,l),l++)}}const S=e=>typeof e=="object"&&e!=null,j=e=>typeof e=="object"?e===null:typeof e!="function",q=e=>e!=="__proto__"&&e!=="constructor"&&e!=="prototype";/*!
 * Based on assign-deep <https://github.com/jonschlinkert/assign-deep>
 *
 * Copyright (c) 2017-present, Jon Schlinkert.
 * Released under the MIT License.
 */const v=(e,...o)=>{let n=0;for(j(e)&&(e=o[n++]),e||(e={});n<o.length;n++)if(S(o[n]))for(const i of Object.keys(o[n]))q(i)&&(S(e[i])&&S(o[n][i])?e[i]=v(Array.isArray(e[i])?[]:{},e[i],o[n][i]):e[i]=o[n][i]);return e},k={cdn:"https://unpkg.com",compression:"gzip",analysis:!1,esbuild:{target:["esnext"],format:"esm",bundle:!0,minify:!0,treeShaking:!0,platform:"browser"}};v({},k,{esbuild:{color:!0,globalName:"BundledCode",logLevel:"info",sourcemap:!1,incremental:!1}});const O=e=>{const o="https://api.npms.io/v2/search?q";let n=`${o}=${encodeURIComponent(e)}&size=30`,i="",s=/([\S]+)@([\S]+)/g.exec(e);if(s){let[,c,l]=s;i=l,n=`${o}=${encodeURIComponent(c)}&size=30`}return{url:n,version:i}},M=e=>(e!=null?e:"").split(/\],/).map(o=>o.replace(/\[|\]/g,"")),$=e=>{try{const o=e.searchParams;let n="",i=o.get("query")||o.get("q"),s=o.get("treeshake");if(i){let m=i.trim().split(","),y=M((s!=null?s:"").trim());n+=`// Click Build for the Bundled, Minified & Compressed package size
`+m.map((C,d)=>{let a=y[d]&&y[d].trim()!=="*"?y[d].trim().split(",").join(", "):"*",[,,u="export",f]=/^(\((.*)\))?(.*)/.exec(C);return`${u} ${a} from ${JSON.stringify(f)};`}).join(`
`)}let c=o.get("share");c&&(n+=`
`+N(c.trim()));let l=o.get("text");return l&&(n+=`
`+JSON.parse(/^["']/.test(l)&&/["']$/.test(l)?l:JSON.stringify(""+l).replace(/\\\\/g,"\\"))),n.trim()}catch{}},H=e=>{var o;try{const i=(o=e.searchParams.get("config"))!=null?o:"{}";return v({},k,JSON.parse(i||"{}"))}catch{}};p.CACHE=b,p.CACHE_NAME=E,p.debounce=g,p.getRequest=T,p.newRequest=A,p.parseConfig=H,p.parseInput=O,p.parseSearchQuery=$,p.parseTreeshakeExports=M,Object.defineProperties(p,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
